src/Entity/Evento.php
<?php

namespace App\Entity;

use App\Repository\EventoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventoRepository::class)]
class Evento
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 350)]
    private ?string $Descripcion = null;

    #[ORM\Column(length: 200)]
    private ?string $Fecha = null;

    #[ORM\Column]
    private ?string $IdTipoEvento = null;

    #[ORM\Column]
    private ?string $IdCategoria = null;

    #[ORM\Column]
    private ?int $IdUsuarioCreacion = null;

    #[ORM\Column(nullable: true)]
    private ?float $Precio = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): static
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getFecha(): ?string
    {
        return $this->Fecha;
    }

    public function setFecha(string $Fecha): static
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    public function getIdTipoEvento(): ?string
    {
        return $this->IdTipoEvento;
    }

    public function setIdTipoEvento(string $IdTipoEvento): static
    {
        $this->IdTipoEvento = $IdTipoEvento;

        return $this;
    }

    public function getIdCategoria(): ?string
    {
        return $this->IdCategoria;
    }

    public function setIdCategoria(string $IdCategoria): static
    {
        $this->IdCategoria = $IdCategoria;

        return $this;
    }

    public function getIdUsuarioCreacion(): ?int
    {
        return $this->IdUsuarioCreacion;
    }

    public function setIdUsuarioCreacion(int $IdUsuarioCreacion): static
    {
        $this->IdUsuarioCreacion = $IdUsuarioCreacion;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->Precio;
    }

    public function setPrecio(?float $Precio): static
    {
        $this->Precio = $Precio;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use App\Repository\EventoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]
    public function index( EventoRepository $eventoRepository): Response
    {

        $eventos_of = $eventoRepository->findBy(array('IdCategoria' => 'En oferta'), array('Nombre' => 'ASC'),5,0);

        $eventos_pr = $eventoRepository->findBy(array('IdCategoria' => 'Proximos'), array('Nombre' => 'ASC'), 5,0);

        $eventos_pa = $eventoRepository->findBy(array('IdCategoria' => 'Pasados'), array('Nombre' => 'ASC'), 5,0);



        return $this->render('home/index.html.twig', [
            'eventos_oferta' => $eventos_of,
            'eventos_proximos' => $eventos_pr,
            'eventos_pasados' => $eventos_pa,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

<div class="container" >
    <header style="background-color: #ededed;" class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <h1>Home</h1>
        </div>
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{{ path('app_home') }}" class="nav-link px-4 link-secondary">Home <i class="bi bi-house"></i></a></li>
            <li><a href="{{ path('Evento_tabla') }}" class="nav-link px-4">Eventos <i class="bi bi-ticket-detailed-fill"></i></a></li>
            <li><a href="{{ path('User_tabla') }}" class="nav-link px-4">Usuarios <i class="bi bi-people-fill"></i></a></li>
        </ul>
        <div class="col-md-3 text-end">
            <a href="{{ path('app_logout') }}"><button type="button" class="btn btn-danger"> 
                Cerrar sesión
                <i class="bi bi-power"></i></button></a>
        </div>
    </header>
</div>
<br>

<div class="container px-4 py-5 " id="featured-3"  >
    <h2 class="pb-2 border-bottom">Eventos en oferta</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3" style="" >
        {% for evento in eventos_oferta %}
        <div class="feature col">
            <div class="text-center">
                <i class="bi bi-ticket-fill"></i>
            </div>
        
            <h3 class="fs-2 text-body-emphasis">{{ evento.nombre }}</h3>
            <p>{{ evento.descripcion }} </p>
            <p>Fecha: {{ evento.fecha }}</p>
            <p>Precio : $ {{ evento.precio }}</p>
            <p>Tipo : {{ evento.IdTipoEvento }}</p>
        </div>

        {% endfor %}

    </div>
</div>

<div class="container px-4 py-5 " id="featured-3">
    <h2 class="pb-2 border-bottom">Eventos próximos</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3" style="">
        {% for evento in eventos_proximos %}
        <div class="feature col">
            <div class="text-center">
                <i class="bi bi-ticket-fill"></i>
            </div>

            <h3 class="fs-2 text-body-emphasis">{{ evento.nombre }}</h3>
            <p>{{ evento.descripcion }} </p>
            <p>Fecha: {{ evento.fecha }}</p>
            <p>Precio : $ {{ evento.precio }}</p>
            <p>Tipo : {{ evento.IdTipoEvento }}</p>
        </div>

        {% endfor %}

    </div>
</div>

<div class="container px-4 py-5 " id="featured-3">
    <h2 class="pb-2 border-bottom">Eventos pasados</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3" >
        {% for evento_p in eventos_pasados %}
        <div class="feature col">
            <div class="text-center">
                <i class="bi bi-ticket-fill"></i>
            </div>

            <h3 class="fs-2 text-body-emphasis">{{ evento_p.nombre }}</h3>
            <p>{{ evento_p.descripcion }} </p>
            <p>Fecha: {{ evento_p.fecha }}</p>
            <p>Precio : $ {{ evento_p.precio }}</p>
            <p>Tipo : {{ evento_p.IdTipoEvento }}</p>
        </div>

        {% endfor %}

    </div>
</div>






{% endblock %}